Merge develop into master
gohypergiant/glossary-bot pull request #6
Opened 2023-09-08 19:01 UTC by imtmcdonald

## Description

- Configured for deployment to fly.io
- Updated dependencies to make the app functional
- Mitigated high vuln

## Related Issue

https://gohypergiant.atlassian.net/browse/OPS-324

## Motivation and Context

Users requested a glossary bot for Slack

## How Has This Been Tested?

Deployed to fly.io and validated via Slack.

## Screenshots (if appropriate):
![image](https://github.com/gohypergiant/glossary-bot/assets/105686517/dd246e95-97f6-48e4-93a6-626b1794c8ec)

2023-09-08 19:03 UTC, imtmcdonald commented
Note, the app is currently spun down in fly.io to save on resources. Once I get the go ahead, I'll spin up.

2023-09-13 19:39 UTC, bbriggs requested changes
Two minor changes. Comments inline.

Also, we might want to consider abstracting the fly deployment workflow now that we're using it across multiple repos. Work for a later PR.

2023-09-13 19:39 UTC, bbriggs commented on .github/workflows/set-fly-app-name.yaml
> +        default: "hg-cc-eph-"
Change prefix default (or drop it altogether).

2023-09-13 19:39 UTC, bbriggs commented on .github/workflows/deploy-to-fly.yaml
> +          -e SLACK_WEBHOOK_URL=${{ vars.SLACK_WEBHOOK_URL }} \
Slack webhooks are sensitive. Make this a secret.

2023-09-14 01:20 UTC, bbriggs approved these changes

2023-09-14 01:21 UTC, merged